# deploy/docker-compose.yml
services:
  api:
    image: ${DOCKERHUB_USERNAME:-axlebits}/catsdogs-api:latest
    ports:
      - "8000:8000"
    volumes:
      - ${MODELS_DIR:-../models}:/app/models:ro
    restart: unless-stopped
